/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
const { v4: uuidv4 } = require('uuid');

exports.seed = async function(knex) {

  await knex('countries').del();

  const countries = [
    {id: uuidv4(), key: "BD", name: "Bangladeş"},
    {id: uuidv4(), key: "BE", name: "Belçika"},
    {id: uuidv4(), key: "BF", name: "Burkina Faso"},
    {id: uuidv4(), key: "BG", name: "Bulgaristan"},
    {id: uuidv4(), key: "BA", name: "Bosna Hersek"},
    {id: uuidv4(), key: "BB", name: "Barbados"},
    {id: uuidv4(), key: "WF", name: "Wallis ve Futuna"},
    {id: uuidv4(), key: "BL", name: "Saint Barthelemy"},
    {id: uuidv4(), key: "BM", name: "Bermuda"},
    {id: uuidv4(), key: "BN", name: "Brunei"},
    {id: uuidv4(), key: "BO", name: "Bolivya"},
    {id: uuidv4(), key: "BH", name: "Bahreyn"},
    {id: uuidv4(), key: "BI", name: "Burundi"},
    {id: uuidv4(), key: "BJ", name: "Benin"},
    {id: uuidv4(), key: "BT", name: "Butan"},
    {id: uuidv4(), key: "JM", name: "Jamaika"},
    {id: uuidv4(), key: "BV", name: "Bouvet Adası"},
    {id: uuidv4(), key: "BW", name: "Botsvana"},
    {id: uuidv4(), key: "WS", name: "Samoa"},
    {id: uuidv4(), key: "BQ", name: "Bonaire, Saint Eustatius ve Saba"},
    {id: uuidv4(), key: "BR", name: "Brezilya"},
    {id: uuidv4(), key: "BS", name: "Bahamalar"},
    {id: uuidv4(), key: "JE", name: "Jersey"},
    {id: uuidv4(), key: "BY", name: "Beyaz Rusya"},
    {id: uuidv4(), key: "BZ", name: "Belize"},
    {id: uuidv4(), key: "RU", name: "Rusya"},
    {id: uuidv4(), key: "RW", name: "Ruanda"},
    {id: uuidv4(), key: "RS", name: "Sırbistan"},
    {id: uuidv4(), key: "TL", name: "Doğu Timor"},
    {id: uuidv4(), key: "RE", name: "Réunion"},
    {id: uuidv4(), key: "TM", name: "Türkmenistan"},
    {id: uuidv4(), key: "TJ", name: "Tacikistan"},
    {id: uuidv4(), key: "RO", name: "Romanya"},
    {id: uuidv4(), key: "TK", name: "Tokelau"},
    {id: uuidv4(), key: "GW", name: "Gine-Bissau"},
    {id: uuidv4(), key: "GU", name: "Guam"},
    {id: uuidv4(), key: "GT", name: "Guatemala"},
    {id: uuidv4(), key: "GS", name: "Güney Georgia ve Güney Sandviç Adaları"},
    {id: uuidv4(), key: "GR", name: "Yunanistan"},
    {id: uuidv4(), key: "GQ", name: "Ekvator Ginesi"},
    {id: uuidv4(), key: "GP", name: "Guadeloupe"},
    {id: uuidv4(), key: "JP", name: "Japonya"},
    {id: uuidv4(), key: "GY", name: "Guyana"},
    {id: uuidv4(), key: "GG", name: "Guernsey"},
    {id: uuidv4(), key: "GF", name: "Fransız Guyanası"},
    {id: uuidv4(), key: "GE", name: "Gürcistan"},
    {id: uuidv4(), key: "GD", name: "Grenada"},
    {id: uuidv4(), key: "GB", name: "Birleşik Krallık"},
    {id: uuidv4(), key: "GA", name: "Gabon"},
    {id: uuidv4(), key: "SV", name: "El Salvador"},
    {id: uuidv4(), key: "GN", name: "Gine"},
    {id: uuidv4(), key: "GM", name: "Gambiya"},
    {id: uuidv4(), key: "GL", name: "Grönland"},
    {id: uuidv4(), key: "GI", name: "Cebelitarık"},
    {id: uuidv4(), key: "GH", name: "Gana"},
    {id: uuidv4(), key: "OM", name: "Umman"},
    {id: uuidv4(), key: "TN", name: "Tunus"},
    {id: uuidv4(), key: "JO", name: "Ürdün"},
    {id: uuidv4(), key: "IK", name: "Hırvatistan"},
    {id: uuidv4(), key: "HT", name: "Haiti"},
    {id: uuidv4(), key: "HU", name: "Macaristan"},
    {id: uuidv4(), key: "HK", name: "Hong Kong"},
    {id: uuidv4(), key: "HN", name: "Honduras"},
    {id: uuidv4(), key: "HM", name: "Heard Adası ve McDonald Adaları"},
    {id: uuidv4(), key: "VE", name: "Venezüella"},
    {id: uuidv4(), key: "PR", name: "Porto Riko"},
    {id: uuidv4(), key: "PW", name: "Palau"},
    {id: uuidv4(), key: "PT", name: "Portekiz"},
    {id: uuidv4(), key: "SJ", name: "Svalbard"},
    {id: uuidv4(), key: "PY", name: "Paraguay"},
    {id: uuidv4(), key: "IQ", name: "Irak"},
    {id: uuidv4(), key: "PA", name: "Panama"},
    {id: uuidv4(), key: "PF", name: "Fransız Polinezyası"},
    {id: uuidv4(), key: "PG", name: "Papua Yeni Gine"},
    {id: uuidv4(), key: "PE", name: "Peru"},
    {id: uuidv4(), key: "PK", name: "Pakistan"},
    {id: uuidv4(), key: "PH", name: "Filipinler"},
    {id: uuidv4(), key: "PN", name: "Pitcairn Adaları"},
    {id: uuidv4(), key: "PL", name: "Polonya"},
    {id: uuidv4(), key: "PM", name: "Saint Pierre ve Miquelon"},
    {id: uuidv4(), key: "ZM", name: "Zambiya"},
    {id: uuidv4(), key: "EH", name: "Batı Sahra"},
    {id: uuidv4(), key: "EE", name: "Estonya"},
    {id: uuidv4(), key: "EG", name: "Mısır"},
    {id: uuidv4(), key: "ZA", name: "Güney Afrika"},
    {id: uuidv4(), key: "EC", name: "Ekvador"},
    {id: uuidv4(), key: "IT", name: "İtalya"},
    {id: uuidv4(), key: "VN", name: "Vietnam"},
    {id: uuidv4(), key: "SB", name: "Solomon Adaları"},
    {id: uuidv4(), key: "ET", name: "Etiyopya"},
    {id: uuidv4(), key: "SO", name: "Somali"},
    {id: uuidv4(), key: "ZW", name: "Zimbabwe"},
    {id: uuidv4(), key: "SA", name: "Suudi Arabistan"},
    {id: uuidv4(), key: "ES", name: "İspanya"},
    {id: uuidv4(), key: "ER", name: "Eritrea"},
    {id: uuidv4(), key: "ME", name: "Karadağ"},
    {id: uuidv4(), key: "MD", name: "Moldova"},
    {id: uuidv4(), key: "MG", name: "Madagaskar"},
    {id: uuidv4(), key: "MF", name: "Saint Martin"},
    {id: uuidv4(), key: "MA", name: "Fas"},
    {id: uuidv4(), key: "MC", name: "Monaco"},
    {id: uuidv4(), key: "UZ", name: "Özbekistan"},
    {id: uuidv4(), key: "MM", name: "Myanmar"},
    {id: uuidv4(), key: "ML", name: "Mali"},
    {id: uuidv4(), key: "MO", name: "Macao"},
    {id: uuidv4(), key: "MN", name: "Moğolistan"},
    {id: uuidv4(), key: "MH", name: "Marshall Adaları"},
    {id: uuidv4(), key: "MK", name: "Makedonya"},
    {id: uuidv4(), key: "MU", name: "Mauritius"},
    {id: uuidv4(), key: "MT", name: "Malta"},
    {id: uuidv4(), key: "MW", name: "Malavi"},
    {id: uuidv4(), key: "MV", name: "Maldivler"},
    {id: uuidv4(), key: "MQ", name: "Martinik"},
    {id: uuidv4(), key: "MP", name: "Kuzey Mariana Adaları"},
    {id: uuidv4(), key: "MS", name: "Montserrat"},
    {id: uuidv4(), key: "MR", name: "Moritanya"},
    {id: uuidv4(), key: "IM", name: "Isle of Man"},
    {id: uuidv4(), key: "UG", name: "Uganda"},
    {id: uuidv4(), key: "TZ", name: "Tanzanya"},
    {id: uuidv4(), key: "MY", name: "Malezya"},
    {id: uuidv4(), key: "MX", name: "Meksika"},
    {id: uuidv4(), key: "IL", name: "İsrail"},
    {id: uuidv4(), key: "FR", name: "Fransa"},
    {id: uuidv4(), key: "IO", name: "İngiliz Hint Okyanusu Bölgesi"},
    {id: uuidv4(), key: "SH", name: "Saint Helena"},
    {id: uuidv4(), key: "FI", name: "Finlandiya"},
    {id: uuidv4(), key: "FJ", name: "Fiji"},
    {id: uuidv4(), key: "FK", name: "Falkland Adaları"},
    {id: uuidv4(), key: "FM", name: "Mikronezya"},
    {id: uuidv4(), key: "FO", name: "Faroe Adaları"},
    {id: uuidv4(), key: "NI", name: "Nikaragua"},
    {id: uuidv4(), key: "NL", name: "Hollanda"},
    {id: uuidv4(), key: "NO", name: "Norveç"},
    {id: uuidv4(), key: "NA", name: "Namibya"},
    {id: uuidv4(), key: "VU", name: "Vanuatu"},
    {id: uuidv4(), key: "NC", name: "Yeni Kaledonya"},
    {id: uuidv4(), key: "NE", name: "Nijer"},
    {id: uuidv4(), key: "NF", name: "Norfolk Adası"},
    {id: uuidv4(), key: "NG", name: "Nijerya"},
    {id: uuidv4(), key: "NZ", name: "Yeni Zelanda"},
    {id: uuidv4(), key: "NP", name: "Nepal"},
    {id: uuidv4(), key: "NR", name: "Nauru"},
    {id: uuidv4(), key: "NU", name: "Niue"},
    {id: uuidv4(), key: "CK", name: "Cook Adaları"},
    {id: uuidv4(), key: "XK", name: "Kosova"},
    {id: uuidv4(), key: "CI", name: "Fildişi Sahilleri"},
    {id: uuidv4(), key: "CH", name: "İsviçre"},
    {id: uuidv4(), key: "CO", name: "Kolombiya"},
    {id: uuidv4(), key: "CN", name: "Çin"},
    {id: uuidv4(), key: "CM", name: "Kamerun"},
    {id: uuidv4(), key: "CL", name: "Şili"},
    {id: uuidv4(), key: "CC", name: "Cocos Adaları"},
    {id: uuidv4(), key: "CA", name: "Kanada"},
    {id: uuidv4(), key: "CG", name: "Kongo Cumhuriyeti"},
    {id: uuidv4(), key: "CF", name: "Orta Afrika Cumhuriyeti"},
    {id: uuidv4(), key: "CD", name: "Demokratik Kongo Cumhuriyeti"},
    {id: uuidv4(), key: "CZ", name: "Çek Cumhuriyeti"},
    {id: uuidv4(), key: "CY", name: "Kıbrıs"},
    {id: uuidv4(), key: "CX", name: "Noel Adası"},
    {id: uuidv4(), key: "CR", name: "Kosta Rika"},
    {id: uuidv4(), key: "CW", name: "Curacao"},
    {id: uuidv4(), key: "CV", name: "Cape Verde"},
    {id: uuidv4(), key: "CU", name: "Küba"},
    {id: uuidv4(), key: "SZ", name: "Svaziland"},
    {id: uuidv4(), key: "SY", name: "Suriye"},
    {id: uuidv4(), key: "SX", name: "Sint Maarten"},
    {id: uuidv4(), key: "KG", name: "Kırgızistan"},
    {id: uuidv4(), key: "KE", name: "Kenya"},
    {id: uuidv4(), key: "SS", name: "Güney Sudan"},
    {id: uuidv4(), key: "SR", name: "Surinam"},
    {id: uuidv4(), key: "KI", name: "Kiribati"},
    {id: uuidv4(), key: "KH", name: "Kamboçya"},
    {id: uuidv4(), key: "KN", name: "Saint Kitts ve Nevis"},
    {id: uuidv4(), key: "KM", name: "Komor"},
    {id: uuidv4(), key: "ST", name: "Sao Tome ve Principe"},
    {id: uuidv4(), key: "SK", name: "Slovakya"},
    {id: uuidv4(), key: "KR", name: "Güney Kore"},
    {id: uuidv4(), key: "SI", name: "Slovenya"},
    {id: uuidv4(), key: "KP", name: "Kuzey Kore"},
    {id: uuidv4(), key: "KW", name: "Kuveyt"},
    {id: uuidv4(), key: "SN", name: "Senegal"},
    {id: uuidv4(), key: "SM", name: "San Marino"},
    {id: uuidv4(), key: "SL", name: "Sierra Leone"},
    {id: uuidv4(), key: "SC", name: "Seyşel Adaları"},
    {id: uuidv4(), key: "KZ", name: "Kazakistan"},
    {id: uuidv4(), key: "KY", name: "Kayman Adaları"},
    {id: uuidv4(), key: "SG", name: "Singapur"},
    {id: uuidv4(), key: "SE", name: "İsveç"},
    {id: uuidv4(), key: "SD", name: "Sudan"},
    {id: uuidv4(), key: "DO", name: "Dominik Cumhuriyeti"},
    {id: uuidv4(), key: "DM", name: "Dominika"},
    {id: uuidv4(), key: "DJ", name: "Cibuti"},
    {id: uuidv4(), key: "DK", name: "Danimarka"},
    {id: uuidv4(), key: "VG", name: "İngiliz Virgin Adaları"},
    {id: uuidv4(), key: "DE", name: "Almanya"},
    {id: uuidv4(), key: "YE", name: "Yemen"},
    {id: uuidv4(), key: "DZ", name: "Cezayir"},
    {id: uuidv4(), key: "ABD", name: "Amerika Birleşik Devletleri"},
    {id: uuidv4(), key: "UY", name: "Uruguay"},
    {id: uuidv4(), key: "YT", name: "Mayotte"},
    {id: uuidv4(), key: "UM", name: "Birleşik Devletlerin Küçük Dış Adaları"},
    {id: uuidv4(), key: "LB", name: "Lübnan"},
    {id: uuidv4(), key: "LC", name: "Saint Lucia"},
    {id: uuidv4(), key: "LA", name: "Laos"},
    {id: uuidv4(), key: "TV", name: "Tuvalu"},
    {id: uuidv4(), key: "TW", name: "Tayvan"},
    {id: uuidv4(), key: "TT", name: "Trinidad ve Tobago"},
    {id: 'c8134f9f-e66c-46c4-b04b-adec068e5ce5', key: "TR", name: "Türkiye"},
    {id: uuidv4(), key: "LK", name: "Sri Lanka"},
    {id: uuidv4(), key: "LI", name: "Lihtenştayn"},
    {id: uuidv4(), key: "AG", name: "Letonya"}
    ];

    const data = countries.map(country => ({
      ...country,
      created_at: new Date(),
      updated_at: new Date(),
    }));
  
    await knex('countries').insert(data);

};
